# Generated by Django 5.1.2 on 2024-10-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
