# Generated by Django 5.1.2 on 2024-10-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_persona',
            field=models.CharField(choices=[('FISICA', 'FISICA'), ('JURIDICA', 'JURIDICA')], max_length=20),
        ),
    ]
