# Generated by Django 5.1.2 on 2024-10-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleado_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cuit',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
