# Generated by Django 5.1.2 on 2024-10-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleado_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cuit',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
