# Generated by Django 5.1.2 on 2024-10-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_alter_empleado_fecha_nacido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='cuit',
            new_name='cuit_cuil',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
    ]
