# Generated by Django 5.1.2 on 2024-11-04 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_rename_cuit_empleado_cuit_cuil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,10}$', message='Formato: +999999999. Hasta 10 dígitos.')]),
        ),
    ]
