# Generated by Django 5.1.2 on 2024-11-02 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_insumo_estado_alter_producto_estado'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('insumo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.insumo')),
                ('pedido_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.pedido')),
            ],
        ),
    ]
