# Generated by Django 5.1.2 on 2024-11-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_itempedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='numero',
            new_name='numero_pedido',
        ),
    ]
