# Generated by Django 5.1.2 on 2024-11-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_pedido_observacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='insumo_id',
            new_name='insumo',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
    ]
