# Generated by Django 5.1.2 on 2024-11-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_rename_insumo_id_itempedido_insumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_realizado',
            field=models.DateField(auto_now_add=True),
        ),
    ]
