# Generated by Django 5.1.2 on 2024-11-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_alter_pedido_fecha_realizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='cantidad',
            new_name='cantidad_pedida',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='cantidad_recibida',
            field=models.IntegerField(default=0),
        ),
    ]
