# Generated by Django 5.1.2 on 2024-11-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_recepcionpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('RECIBIDO', 'RECIBIDO')], default='PENDIENTE', max_length=25),
        ),
    ]
