# Generated by Django 5.1.2 on 2024-10-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cuit',
            field=models.CharField(default='01234567890', max_length=11, unique=True),
        ),
    ]
