# Generated by Django 5.1.2 on 2024-10-23 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida_nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('cantidad_minima', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_mayorista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria', to='inventario.categoria')),
                ('unidad_de_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.unidaddemedida')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('cantidad_minima', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('ultimo_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('unidad_de_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.unidaddemedida')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
