# Generated by Django 5.1.2 on 2024-11-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_insumo_estado_alter_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_mayorista',
        ),
    ]
