# Generated by Django 5.1.2 on 2024-10-21 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoria_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidad_medida', to='inventario.unidaddemedida'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria', to='inventario.categoria'),
        ),
    ]
