# Generated by Django 5.1.2 on 2024-10-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteMayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('mail', models.EmailField(max_length=150)),
                ('tipo_persona', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('calle', models.CharField(max_length=150)),
                ('localidad', models.CharField(max_length=150)),
                ('numero_calle', models.IntegerField(null=True)),
                ('fecha_nacido', models.DateTimeField()),
                ('codicionIVA', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
