# Generated by Django 5.1.2 on 2024-10-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_mayorista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemayorista',
            name='tipo_persona',
            field=models.CharField(choices=[('FISICA', 'FISICA'), ('JURIDICA', 'JURIDICA')], max_length=20),
        ),
    ]
