# Generated by Django 5.1.2 on 2024-10-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_mayorista', '0003_alter_clientemayorista_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemayorista',
            name='fecha_nacido',
            field=models.DateField(),
        ),
    ]
