# Generated by Django 5.1.2 on 2024-10-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_mayorista', '0004_alter_clientemayorista_fecha_nacido'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemayorista',
            name='cuit_cuil',
            field=models.CharField(default=12345678901, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
