# Generated by Django 5.1.2 on 2024-10-31 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_mayorista', '0005_clientemayorista_cuit_cuil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientemayorista',
            old_name='codicionIVA',
            new_name='condicionIVA',
        ),
    ]
