# Generated by Django 5.1.2 on 2024-10-21 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_alter_insumo_unidad_de_medida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('empleado', models.IntegerField()),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('forma_de_pago', models.CharField(max_length=20)),
                ('tipo_comprobante', models.CharField(max_length=20)),
                ('comprador', models.CharField(max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=150)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
                ('venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='ventas.venta')),
            ],
        ),
    ]
