# Generated by Django 5.1.2 on 2024-10-29 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_mayorista', '0004_alter_clientemayorista_fecha_nacido'),
        ('empleados', '0007_alter_empleado_fecha_nacido'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente_mayorista.clientemayorista'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_de_pago',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TRASNFERENCIA', 'TRASNFERENCIA'), ('TARJETA', 'TARJETA'), ('QR', 'QR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_comprobante',
            field=models.CharField(choices=[('TICKET', 'TICKET'), ('FACTURA', 'FACTURA')], max_length=20),
        ),
    ]
