# Generated by Django 5.1.2 on 2024-10-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='codigo',
        ),
    ]
