# Generated by Django 5.1.2 on 2024-11-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_mayorista', '0006_rename_codicioniva_clientemayorista_condicioniva'),
        ('ventas', '0003_alter_venta_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente_mayorista.clientemayorista'),
        ),
    ]
