# Generated by Django 5.1.2 on 2024-11-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_remove_venta_comprador_itemmayorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_comprobante',
            field=models.TextField(default='00000'),
        ),
    ]
