# Generated by Django 5.1.2 on 2024-10-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedor_fecha_nacido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='cuit',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuit_cuil',
            field=models.CharField(default=12345678901, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_de_pedido',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_de_reparto',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
