# Generated by Django 5.1.2 on 2024-11-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_proveedor_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='fecha_nacido',
        ),
    ]
